namespace SHARSaveGameEditor
{
    public static class Names
    {
        public static readonly string[] Cards =
        {
            // Level 1
            "card11 (Home Made Football)",
            "card12 (Crab Juice)",
            "card13 (Insanity Pepper)",
            "card14 (Spinemelter 2000)",
            "card15 (Parchment)",
            "card16 (Carbon Rod)",
            "card17 (Mr. Sparkle Box)",
            "UNUSED",
            // Level 2
            "card21 (Head of Jebediah)",
            "card22 (AM Radio Toy)",
            "card23 (Bonestorm Game)",
            "card24 (\"Big Butt Skinner\")",
            "card25 (Mr. Honeybunny)",
            "card26 (Drivers License)",
            "card27 (Pregnancy Test)",
            "UNUSED",
            // Level 3
            "card31 (Angel Skeleton)",
            "card32 (Bart's Soul)",
            "card33 (Lisa Lionheart)",
            "card34 (Lisa's Valentine)",
            "card35 (Lisa's Machine)",
            "card36 (Evil Braces)",
            "card37 (Soy Pop)",
            "UNUSED",
            // Level 4
            "card41 (Mr. Plow Jacket)",
            "card42 (Burns Portrait)",
            "card43 (Love Letter)",
            "card44 (\"Homer\" Bowling Ball)",
            "card45 (Red Blazer)",
            "card46 (Boudoir Album)",
            "card47 (Pepper Spray)",
            "UNUSED",
            // Level 5
            "card51 (Apu's T-Shirt)",
            "card52 (Pin Pals Shirt)",
            "card53 (Prop 24 Sign)",
            "card54 (Baby Feeder)",
            "card55 (Ganesh Costume)",
            "card56 (Chutney Squishee)",
            "card57 (Hot Dog)",
            "UNUSED",
            // Level 6
            "card61 (Radioactive Man#1)",
            "card62 (\"BORT\" License Plate)",
            "card63 (Bart T-Shirt)",
            "card64 (Australia Boot)",
            "card65 (Itchy and Scratchy Cel)",
            "card66 (Garbo Doll)",
            "card67 (Bart's Flying Hamster Science Project)",
            "UNUSED",
            // Level 7
            "card71 (Soul Donut)",
            "card72 (Krusty Doll)",
            "card73 (Human Cookbook)",
            "card74 (Time Travel Toaster)",
            "card75 (Hell Toupee)",
            "card76 (Monkey's Paw)",
            "card77 (\"Smarch\" Calendar)",
            "UNUSED",
        };

        public static readonly string[] Level1PurchasedRewards =
        {
            "Reward 0 (Plow King)",
            "Reward 1 (Duff Truck)",
            "Reward 2 (Surveillance Van)",
            "Reward 3 (Homer - Casual)",
            "Reward 4 (Homer - Muumuu)",
            "Reward 5 (Homer - Chosen One)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level1Gags = {
            "Gag 0 (gag_bbq.p3d)",
            "Gag 1 (gag_gas.p3d)",
            "Gag 2 (gag_shel.p3d)",
            "Gag 3 (gag_swng.p3d)",
            "Gag 4 (gag_swg2.p3d)",
            "Gag 5 (gag_sqsh.p3d)",
            "Gag 6 (gag_jasp.p3d)",
            "Gag 7 (gag_atm.p3d)",
            "Gag 8 (gag_tv.p3d)",
            "Gag 9 (gag_azte.p3d)",
            "Gag 10 (gag_melt.p3d)",
            "Gag 11 (gag_fire.p3d)",
            "Gag 12 (gag_sknr.p3d)",
            "Gag 13 (gag_tele.p3d)",
            "Gag 14 (gag_alm2.p3d)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level1Missions =
        {
            "Mission 0 (The Cola Caper)",
            "Mission 1 (S-M-R-T)",
            "Mission 2 (Petty Theft Homer)",
            "Mission 3 (Office Spaced)",
            "Mission 4 (Blind Big Brother)",
            "Mission 5 (Flowers By Irene)",
            "Mission 6 (Bonestorm Storm)",
            "Mission 7 (The Fat and Furious)",
            "Bonus Mission (This Old Shanty)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] Level2PurchasedRewards =
        {
            "Reward 0 (Mr. Plow)",
            "Reward 1 (Limo)",
            "Reward 2 (Fire Truck)",
            "Reward 3 (Bart - Tall)",
            "Reward 4 (Bart - Football)",
            "Reward 5 (Bart - Ninja)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level2Gags = {
            "Gag 0 (gag_jar.p3d)",
            "Gag 1 (gag_flm.p3d)",
            "Gag 2 (gag_love.p3d)",
            "Gag 3 (gag_slot.p3d)",
            "Gag 4 (gag_cata.p3d)",
            "Gag 5 (gag_tony.p3d)",
            "Gag 6 (gag_bomb.p3d)",
            "Gag 7 (gag_milk.p3d)",
            "Gag 8 (gag_car.p3d)",
            "Gag 9 (gag_mol2.p3d)",
            "Gag 10 (l2_dump.p3d)",
            "Gag 11 (unused)",
            "Gag 12 (unused)",
            "Gag 13 (unused)",
            "Gag 14 (unused)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level2Missions =
        {
            "Mission 1 (Detention Deficit Disorder)",
            "Mission 2 (Weapons of Mass Delinquency)",
            "Mission 3 (Vox Nerduli)",
            "Mission 4 (Bart 'n' Frink)",
            "Mission 5 (Better Than Beef)",
            "Mission 6 (Monkey See Monkey D'oh)",
            "Mission 7 (Cell-Outs)",
            "Mission 8 (Unnamed)",
            "Bonus Mission (Dial B for Blood)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] Level3PurchasedRewards =
        {
            "Reward 0 (School Bus)",
            "Reward 1 (Donut Truck)",
            "Reward 2 (Nerd Car)",
            "Reward 3 (Lisa - Cool)",
            "Reward 4 (Lisa - Floreda)",
            "Reward 5 (Lisa - Hockey)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level3Gags = {
            "Gag 0 (gag_racm.p3d)",
            "Gag 1 (gag_clnk.p3d)",
            "Gag 2 (gag_flag.p3d)",
            "Gag 3 (gag_pig.p3d)",
            "Gag 4 (gag_alrm.p3d)",
            "Gag 5 (gag_matt.p3d)",
            "Gag 6 (gag_perp.p3d)",
            "Gag 7 (gag_pant.p3d)",
            "Gag 8 (gag_kids.p3d)",
            "Gag 9 (gag_tele.p3d)",
            "Gag 10 (l3_dump.p3d)",
            "Gag 11 (unused)",
            "Gag 12 (unused)",
            "Gag 13 (unused)",
            "Gag 14 (unused)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level3Missions =
        {
            "Mission 1 (Nerd Race Queen)",
            "Mission 2 (Clueless)",
            "Mission 3 (Bonfire of the Manatees)",
            "Mission 4 (Operation Hellfish)",
            "Mission 5 (Slithery Sleuthing)",
            "Mission 6 (Fishy Deals)",
            "Mission 7 (The Old Pirate and the Sea)",
            "Mission 8 (Unnamed)",
            "Bonus Mission (Princi-pal)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] Level4PurchasedRewards =
        {
            "Reward 0 (Tractor)",
            "Reward 1 (Krusty's Limo)",
            "Reward 2 (Curator)",
            "Reward 3 (Marge - Inmate)",
            "Reward 4 (Marge - Classy)",
            "Reward 5 (Marge - Police)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level4Gags = {
            "Gag 0 (l04_bbq.p3d)",
            "Gag 1 (l04_gas.p3d)",
            "Gag 2 (gag_shel.p3d)",
            "Gag 3 (l04_swng.p3d)",
            "Gag 4 (gag_sqsh.p3d)",
            "Gag 5 (gag_jasp.p3d)",
            "Gag 6 (gag_atm.p3d)",
            "Gag 7 (gag_tv.p3d)",
            "Gag 8 (l04_azte.p3d)",
            "Gag 9 (gag_melt.p3d)",
            "Gag 10 (gag_fire.p3d)",
            "Gag 11 (gag_sknr.p3d)",
            "Gag 12 (gag_lamp.p3d)",
            "Gag 13 (gag_tele.p3d)",
            "Gag 14 (gag_alm2.p3d)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level4Missions =
        {
            "Mission 1 (For A Few Donuts More)",
            "Mission 2 (Redneck Roundup)",
            "Mission 3 (Ketchup Logic)",
            "Mission 4 (Return of the Nearly-Dead)",
            "Mission 5 (Wolves Stole My Pills)",
            "Mission 6 (The Cola Wars)",
            "Mission 7 (From Outer Space)",
            "Mission 8 (Unnamed)",
            "Bonus Mission (Beached Love)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] Level5PurchasedRewards =
        {
            "Reward 0 (Car Built For Homer)",
            "Reward 1 (Police Car)",
            "Reward 2 (Cola Truck)",
            "Reward 3 (Apu - Army)",
            "Reward 4 (Apu - American)",
            "Reward 5 (Apu - B-sharps)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level5Gags = {
            "Gag 0 (gag_jar.p3d)",
            "Gag 1 (gag_flm.p3d)",
            "Gag 2 (gag_love.p3d)",
            "Gag 3 (gag_slot.p3d)",
            "Gag 4 (gag_mol2.p3d)",
            "Gag 5 (l5_dump.p3d)",
            "Gag 6 (unused)",
            "Gag 7 (unused)",
            "Gag 8 (unused)",
            "Gag 9 (unused)",
            "Gag 10 (unused)",
            "Gag 11 (unused)",
            "Gag 12 (unused)",
            "Gag 13 (unused)",
            "Gag 14 (unused)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level5Missions =
        {
            "Mission 1 (Incriminating Caffeine)",
            "Mission 2 (. . . and Baby Makes 8)",
            "Mission 3 (Eight is Too Much)",
            "Mission 4 (This Little Piggy)",
            "Mission 5 (Never Trust a Snake)",
            "Mission 6 (Kiwk Cash)",
            "Mission 7 (Curious Curator)",
            "Mission 8 (Unnamed)",
            "Bonus Mission (Kinky Frinky)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] Level6PurchasedRewards =
        {
            "Reward 0 (Globex Super Villain Car)",
            "Reward 1 (Armored Truck)",
            "Reward 2 (Chase Sedan)",
            "Reward 3 (Bart - Hugo)",
            "Reward 4 (Bart - Cadet)",
            "Reward 5 (Bart - Bartman)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level6Gags = {
            "Gag 0 (gag_racm.p3d)",
            "Gag 1 (gag_clnk.p3d)",
            "Gag 2 (l06_flag.p3d)",
            "Gag 3 (l06_pig.p3d)",
            "Gag 4 (gag_alrm.p3d)",
            "Gag 5 (gag_matt.p3d)",
            "Gag 6 (gag_perp.p3d)",
            "Gag 7 (l06_pant.p3d)",
            "Gag 8 (gag_kids.p3d)",
            "Gag 9 (gag_tele.p3d)",
            "Gag 10 (l6_dump.p3d)",
            "Gag 11 (unused)",
            "Gag 12 (unused)",
            "Gag 13 (unused)",
            "Gag 14 (unused)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level6Missions =
        {
            "Mission 1 (Going to the Lu')",
            "Mission 2 (Getting Down with the Clown)",
            "Mission 3 (Lab Coat Caper)",
            "Mission 4 (Duff for Me, Duff for You)",
            "Mission 5 (Full Metal Jackass)",
            "Mission 6 (Set to Kill)",
            "Mission 7 (Kang and Kodos Strike Back)",
            "Mission 8 (Unnamed)",
            "Bonus Mission (Milking the Pigs)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] Level7PurchasedRewards =
        {
            "Reward 0 (Zombie Car)",
            "Reward 1 (Hover Bike)",
            "Reward 2 (Hearse)",
            "Reward 3 (Homer - Dirty)",
            "Reward 4 (Homer - Evil)",
            "Reward 5 (Homer - Donut)",
            "Reward 6 (Unused)",
            "Reward 7 (Unused)",
            "Reward 8 (Unused)",
            "Reward 9 (Unused)",
            "Reward 10 (Unused)",
            "Reward 11 (Unused)",
        };

        public static readonly string[] Level7Gags = {
            "Gag 0 (l07_gas.p3d)",
            "Gag 1 (l07_swng.p3d)",
            "Gag 2 (l07_swg2.p3d)",
            "Gag 3 (gag_sqsh.p3d)",
            "Gag 4 (gag_jasp.p3d)",
            "Gag 5 (gag_atm.p3d)",
            "Gag 6 (gag_tv.p3d)",
            "Gag 7 (l07_azte.p3d)",
            "Gag 8 (gag_fire.p3d)",
            "Gag 9 (gag_sknr.p3d)",
            "Gag 10 (gag_tele.p3d)",
            "Gag 11 (gag_alm2.p3d)",
            "Gag 12 (gag_lamp.p3d)",
            "Gag 13 (gag_bed.p3d)",
            "Gag 14 (l07_shel.p3d)",
            "Gag 15 (unused)",
            "Gag 16 (unused)",
            "Gag 17 (unused)",
            "Gag 18 (unused)",
            "Gag 19 (unused)",
            "Gag 20 (unused)",
            "Gag 21 (unused)",
            "Gag 22 (unused)",
            "Gag 23 (unused)",
            "Gag 24 (unused)",
            "Gag 25 (unused)",
            "Gag 26 (unused)",
            "Gag 27 (unused)",
            "Gag 28 (unused)",
            "Gag 29 (unused)",
            "Gag 30 (unused)",
            "Gag 31 (unused)",
        };

        public static readonly string[] Level7Missions =
        {
            "Mission 1 (Rigor Motors)",
            "Mission 2 (Long Black Probes)",
            "Mission 3 (Pocket Protector)",
            "Mission 4 (There's Something About Monty)",
            "Mission 5 (Alien \"Auto\"topsy Part I)",
            "Mission 6 (Alien \"Auto\"topsy Part II)",
            "Mission 7 (Alien \"Auto\"topsy Part III)",
            "Mission 8 (Unnamed)",
            "Bonus Mission (Flaming Tires)",
            "Race 1 (Time Trial)",
            "Race 2 (Circuit Race)",
            "Race 3 (Checkpoint Race)",
            "Race 4 (Wager Race)",
        };

        public static readonly string[] PersistentObjectStateSectors =
        {
            "l1r1.p3d",
            "l1r2.p3d",
            "l1r3.p3d",
            "l1r4a.p3d",
            "l1r4b.p3d",
            "l1r6.p3d",
            "l1r7.p3d",
            "l1z1.p3d",
            "l1z2.p3d",
            "l1z3.p3d",
            "l1z4.p3d",
            "l1z6.p3d",
            "l1z7.p3d",
            "l2r1.p3d",
            "l2r2.p3d",
            "l2r3.p3d",
            "l2r4.p3d",
            "l2z1.p3d",
            "l2z2.p3d",
            "l2z3.p3d",
            "l2z4.p3d",
            "l3r1.p3d",
            "l3r2.p3d",
            "l3r3.p3d",
            "l3r4.p3d",
            "l3r5.p3d",
            "l3z1.p3d",
            "l3z2.p3d",
            "l3z3.p3d",
            "l3z4.p3d",
            "l3z5.p3d",
            "l4r1.p3d",
            "l4r2.p3d",
            "l4r3.p3d",
            "l4r4a.p3d",
            "l4r4b.p3d",
            "l4r6.p3d",
            "l4r7.p3d",
            "l4z1.p3d",
            "l4z2.p3d",
            "l4z3.p3d",
            "l4z4.p3d",
            "l4z6.p3d",
            "l4z7.p3d",
            "l5r1.p3d",
            "l5r2.p3d",
            "l5r3.p3d",
            "l5r4.p3d",
            "l5z1.p3d",
            "l5z2.p3d",
            "l5z3.p3d",
            "l5z4.p3d",
            "l6r1.p3d",
            "l6r2.p3d",
            "l6r3.p3d",
            "l6r4.p3d",
            "l6r5.p3d",
            "l6z1.p3d",
            "l6z2.p3d",
            "l6z3.p3d",
            "l6z4.p3d",
            "l6z5.p3d",
            "l7r1.p3d",
            "l7r2.p3d",
            "l7r3.p3d",
            "l7r4a.p3d",
            "l7r4b.p3d",
            "l7r6.p3d",
            "l7r7.p3d",
            "l7z1.p3d",
            "l7z2.p3d",
            "l7z3.p3d",
            "l7z4.p3d",
            "l7z6.p3d",
            "l7z7.p3d",
            "Level 1",
            "Level 2",
            "Level 3",
            "Level 4",
            "Level 5",
            "Level 6",
            "Level 7",
        };
    }
}
